# Generated by Django 4.0.6 on 2022-10-18 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='uid',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi identifikatsiya raqami'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Tasdiqlangan holati: '),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name="To'lanish holati: "),
        ),
    ]
