# Generated by Django 4.0.6 on 2022-07-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_post_travel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tassurotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=50)),
                ('qisqa_mal', models.CharField(max_length=200)),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
                ('toliq_mal', models.TextField()),
            ],
        ),
    ]
