# Generated by Django 4.0.6 on 2022-07-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_travel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='image',
            new_name='picture',
        ),
    ]
