# Generated by Django 4.0.6 on 2022-07-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_rename_image_travel_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tassurotlar',
            name='picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Rasmni joylang:'),
        ),
        migrations.AlterField(
            model_name='tassurotlar',
            name='qisqa_mal',
            field=models.CharField(max_length=200, verbose_name="Qiqacha ma'lumot"),
        ),
        migrations.AlterField(
            model_name='tassurotlar',
            name='sarlavha',
            field=models.CharField(max_length=50, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='tassurotlar',
            name='toliq_mal',
            field=models.TextField(verbose_name="To'liq ma'lumot"),
        ),
        migrations.AlterField(
            model_name='tassurotlar',
            name='vaqt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vaqtni avtomat tanlaydi.'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='davomiyligi',
            field=models.CharField(max_length=20, verbose_name='Sayohat davomiyligi:'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='narxi',
            field=models.CharField(max_length=20, verbose_name='Sayohat narxi'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Rasmni joylang:'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='qayerdan',
            field=models.CharField(max_length=50, verbose_name='Qayerdan:'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='qayerga',
            field=models.CharField(max_length=50, verbose_name='Qayerga:'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='qisqa_mal',
            field=models.TextField(verbose_name="Qisqacha ma'lumot:"),
        ),
        migrations.AlterField(
            model_name='travel',
            name='toliq_mal',
            field=models.TextField(verbose_name="To'liq ma'lumot:"),
        ),
    ]
