# Generated by Django 4.0.6 on 2022-07-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_tassurotlar_picture_alter_tassurotlar_qisqa_mal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rasmlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Rasmni joylang:')),
                ('name', models.CharField(max_length=20, verbose_name='Rasmning nomi:')),
            ],
        ),
    ]
