# Generated by Django 4.0.6 on 2022-07-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_tassurotlar_updated_alter_tassurotlar_vaqt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tassurotlar',
            name='vaqt',
        ),
    ]
