# Generated by Django 4.0.6 on 2022-07-24 05:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_tassurotlar_vaqt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tassurotlar',
            name='toliq_mal',
            field=ckeditor.fields.RichTextField(verbose_name="To'liq ma'lumot"),
        ),
        migrations.AlterField(
            model_name='travel',
            name='toliq_mal',
            field=ckeditor.fields.RichTextField(verbose_name="To'liq ma'lumot:"),
        ),
    ]
