# Generated by Django 4.0.6 on 2022-07-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_tassurotlar_toliq_mal_alter_travel_toliq_mal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fikrlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Ism, familiyangizni kiriting: ')),
                ('text', models.TextField(verbose_name='Fikrlaringizni kiriting: ')),
            ],
        ),
    ]
