# Generated by Django 4.0.6 on 2022-07-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_fikrlar_date_alter_fikrlar_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Transport nomini kiriting:')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Transport rasmini joylang: ')),
            ],
        ),
        migrations.RemoveField(
            model_name='fikrlar',
            name='date',
        ),
    ]
