# Generated by Django 4.0.6 on 2022-09-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_transport_remove_fikrlar_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rasmlar',
            options={'verbose_name': 'Rasmlar', 'verbose_name_plural': 'Rasmlar'},
        ),
        migrations.AlterModelOptions(
            name='tassurotlar',
            options={'verbose_name': 'Yangiliklar', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': 'Transport', 'verbose_name_plural': 'Transport'},
        ),
        migrations.AlterModelOptions(
            name='travel',
            options={'verbose_name': 'Sayohatlar', 'verbose_name_plural': 'Sayohatlar'},
        ),
        migrations.AddField(
            model_name='travel',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='travel',
            name='narxi',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Sayohat narxi'),
        ),
    ]
