# Generated by Django 4.0.6 on 2022-09-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_rasmlar_options_alter_tassurotlar_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_payed', models.BooleanField(default=False)),
                ('where_from', models.CharField(max_length=255)),
                ('where_to', models.CharField(max_length=255)),
                ('package', models.CharField(max_length=255)),
                ('customer_phone_number', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('start_date', models.IntegerField()),
                ('end_date', models.IntegerField()),
            ],
        ),
    ]
