# Generated by Django 4.0.6 on 2022-10-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AlterModelOptions(
            name='rasmlar',
            options={'verbose_name': 'Rasm', 'verbose_name_plural': 'Rasmlar'},
        ),
        migrations.AlterModelOptions(
            name='tassurotlar',
            options={'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='travel',
            options={'verbose_name': 'Sayohat', 'verbose_name_plural': 'Sayohatlar'},
        ),
        migrations.RemoveField(
            model_name='travel',
            name='is_payed',
        ),
    ]
