# Generated by Django 4.0.6 on 2022-10-19 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_delete_order_alter_rasmlar_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tassurotlar',
        ),
    ]
