# Generated by Django 4.0.6 on 2022-10-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_delete_tassurotlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='payed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Transport narxi:'),
            preserve_default=False,
        ),
    ]
