# Generated by Django 4.0.6 on 2022-10-19 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_transport_payed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='payed',
        ),
    ]
